/**
 * Generated by tsnapi — public API snapshot of `whenexpr` */
// Interfaces
export interface EvaluateOptions {
  strict?: boolean;
}

// Types
export type BinaryOp = '||' | '&&' | '==' | '!=' | '===' | '!==' | '<' | '>' | '<=' | '>=' | '+' | '-' | '*' | '/' | '%';
export type UnaryOp = '!' | '-' | '+';
export type WhenNode = {
  type: 'literal';
  value: boolean | number | string;
} | {
  type: 'key';
  key: string;
} | {
  type: 'unary';
  op: UnaryOp;
  operand: WhenNode;
} | {
  type: 'binary';
  op: BinaryOp;
  left: WhenNode;
  right: WhenNode;
};

// Functions
export declare function evaluate<T extends Record<string, unknown>>(_: WhenNode, _: T, _?: EvaluateOptions): boolean;
export declare function evaluateWhen<T extends Record<string, unknown>>(_: string, _: T, _?: EvaluateOptions): boolean;
export declare function parse(_: string): WhenNode;
export declare function resolveContextValue<T extends Record<string, unknown>>(_: string, _: T): unknown;