/**
 * Generated by tsnapi — public API snapshot of `whenexpr` */
// Interfaces
export interface EvaluateOptions {
  strict?: boolean;
}

// Types
export type BinaryOp = '||' | '&&' | '==' | '!=' | '===' | '!==' | '<' | '>' | '<=' | '>=' | '+' | '-' | '*' | '/' | '%';
export type ContextPaths<T, P extends string = ''> = { [K in keyof T & string]: `${P}${K}` | (T[K] extends readonly unknown[] ? never : T[K] extends ((...args: never[]) => unknown) ? never : T[K] extends object ? ContextPaths<T[K], `${P}${K}.`> | ContextPaths<T[K], `${P}${K}:`> : never) }[keyof T & string];
export type UnaryOp = '!' | '-' | '+';
export type ValidateExpression<S extends string, T> = string extends S ? S : Tokenize<S> extends infer Toks ? Toks extends TokErr ? WhenExpressionError<`Syntax error: ${Toks['__err']}`> : Toks extends Tok[] ? Parse<Toks> extends [infer N extends Ast, [{
  k: 'eof';
}]] ? [keyof T] extends [never] ? S : string extends keyof T ? S : Exclude<CollectKeys<N>, ContextPaths<T>> extends infer Missing ? [Missing] extends [never] ? S : WhenExpressionError<`Unknown context key: "${Extract<Missing, string>}"`> : never : WhenExpressionError<'Syntax error in expression'> : never : never;
export type WhenExpression<T, S extends string> = S & ValidateExpression<S, T>;
export type WhenExpressionError<M extends string> = string & {
  readonly __whenExpressionError: M;
};
export type WhenNode = {
  type: 'literal';
  value: boolean | number | string;
} | {
  type: 'key';
  key: string;
} | {
  type: 'unary';
  op: UnaryOp;
  operand: WhenNode;
} | {
  type: 'binary';
  op: BinaryOp;
  left: WhenNode;
  right: WhenNode;
};

// Functions
export declare function evaluate<T extends Record<string, unknown>>(_: WhenNode, _: T, _?: EvaluateOptions): boolean;
export declare function evaluateWhen<T extends object, const E extends string>(_: E & ValidateExpression<E, T>, _: T, _?: EvaluateOptions): boolean;
export declare function parse(_: string): WhenNode;
export declare function resolveContextValue<T extends Record<string, unknown>>(_: string, _: T): unknown;